<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <NoWarn>8618;</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUlid" Version="1.7.3" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.150" />
  </ItemGroup>

</Project>
